// PM2 process config for the Next.js standalone server.
// Deployed alongside the standalone bundle and run from the deploy directory.
// `server.js` (generated by `next build` with output: "standalone") reads PORT + HOSTNAME.
module.exports = {
  apps: [
    {
      name: "phonetrade",
      script: "server.js",
      cwd: __dirname,
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        HOSTNAME: "0.0.0.0",
        // Server-only secrets (read at runtime) go here later, e.g.:
        // SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
      },
    },
  ],
};
